version: '3.8'

services:
  product_module:
    env_file:
      - "../.env"
    build:
      context: .
    container_name: product_module
    restart: always
    ports:
      - "9081:8080"
    environment:
      MODULE_GROUP_ID: PRODUCT_GROUP_ID
#    deploy:
#      mode: replicated
#      replicas: 2

